[
    {
        "subtype": "channel_join",
        "user": "UCK7EDQKT",
        "text": "<@UCK7EDQKT> has joined the channel",
        "type": "message",
        "ts": "1535907449.000200"
    },
    {
        "user": "UC70576CB",
        "type": "message",
        "ts": "1535957382.000100",
        "client_msg_id": "dbef67e5-00cd-41ac-a30e-d36975ddd869",
        "text": "Has anyone ran in to this issue before using streaming? It's occurring after the stream has been running for a while, seemingly at random:\n\n```\nException in thread BetfairSocket:\nTraceback (most recent call last):\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 916, in _bootstrap_inner\n    self.run()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 191, in _read_loop\n    received_data_raw = self._receive_all()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 225, in _receive_all\n    data += part.decode(self.__encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 1: invalid continuation byte\n\nException in thread BetfairSocket:\nTraceback (most recent call last):\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 916, in _bootstrap_inner\n    self.run()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 191, in _read_loop\n    received_data_raw = self._receive_all()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 225, in _receive_all\n    data += part.decode(self.__encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 296: invalid start byte\n```",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g3b214cb6303",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/83b214cb63031e2a2ae3958016f7bf23.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0015-72.png",
            "first_name": "",
            "real_name": "Rob",
            "display_name": "Rob",
            "team": "T4G9NBD2M",
            "name": "rnobleeddy",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "lVLhc",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Has anyone ran in to this issue before using streaming? It's occurring after the stream has been running for a while, seemingly at random:\n\n"
                            }
                        ]
                    },
                    {
                        "type": "rich_text_preformatted",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Exception in thread BetfairSocket:\nTraceback (most recent call last):\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 916, in _bootstrap_inner\n    self.run()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 191, in _read_loop\n    received_data_raw = self._receive_all()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 225, in _receive_all\n    data += part.decode(self.__encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 1: invalid continuation byte\n\nException in thread BetfairSocket:\nTraceback (most recent call last):\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 916, in _bootstrap_inner\n    self.run()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\threading.py\", line 864, in run\n    self._target(*self._args, **self._kwargs)\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 191, in _read_loop\n    received_data_raw = self._receive_all()\n  File \"C:\\Users\\username\\Anaconda3\\envs\\pythonBetfairDataGatherer\\lib\\site-packages\\betfairlightweight\\streaming\\betfairstream.py\", line 225, in _receive_all\n    data += part.decode(self.__encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 296: invalid start byte\n"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]