[
    {
        "user": "UE72WCRR8",
        "type": "message",
        "ts": "1611083026.018200",
        "client_msg_id": "372bc513-06ca-45b9-a5ab-70be11861709",
        "text": "I have a bunch of football fixtures in a database and query the inplay scores using the event_ids. Some of those fixtures are accumulators or specials which cause the query to return an error:\n\n`Traceback (most recent call last):`\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/baseendpoint.py\", line 108, in process_response\n    return [resource(elapsed_time=elapsed_time, **x) for x in result]\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/baseendpoint.py\", line 108, in &lt;listcomp&gt;\n    return [resource(elapsed_time=elapsed_time, **x) for x in result]\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/resources\/inplayserviceresources.py\", line 193, in __init__\n    self.score = Score(**kwargs.get(\"score\"))\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/resources\/inplayserviceresources.py\", line 87, in __init__\n    self.home = HomeAwayBase(**home)\nTypeError: __init__() missing 1 required positional argument: 'name'\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"\/home\/code\/PycharmProjects\/betfair_jhaa\/v2\/core\/StreamEngine.py\", line 247, in query_inplay_scores\n    scores = <http:\/\/self.trading.in|self.trading.in>_play_service.get_scores(event_ids=event_ids)\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/inplayservice.py\", line 99, in get_scores\n    return self.process_response(\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/baseendpoint.py\", line 110, in process_response\n    raise InvalidResponse(response=result)\nbetfairlightweight.exceptions.InvalidResponse: Invalid response received:",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "7872271afbd5",
            "image_72": "https:\/\/avatars.slack-edge.com\/2019-09-18\/751973528338_7872271afbd5e88918d9_72.jpg",
            "first_name": "",
            "real_name": "John",
            "display_name": "jhaa",
            "team": "T4G9NBD2M",
            "name": "jhaa",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "ROx",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I have a bunch of football fixtures in a database and query the inplay scores using the event_ids. Some of those fixtures are accumulators or specials which cause the query to return an error:\n\n"
                            },
                            {
                                "type": "text",
                                "text": "Traceback (most recent call last):",
                                "style": {
                                    "code": true
                                }
                            },
                            {
                                "type": "text",
                                "text": "\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/baseendpoint.py\", line 108, in process_response\n    return [resource(elapsed_time=elapsed_time, **x) for x in result]\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/baseendpoint.py\", line 108, in <listcomp>\n    return [resource(elapsed_time=elapsed_time, **x) for x in result]\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/resources\/inplayserviceresources.py\", line 193, in __init__\n    self.score = Score(**kwargs.get(\"score\"))\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/resources\/inplayserviceresources.py\", line 87, in __init__\n    self.home = HomeAwayBase(**home)\nTypeError: __init__() missing 1 required positional argument: 'name'\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"\/home\/code\/PycharmProjects\/betfair_jhaa\/v2\/core\/StreamEngine.py\", line 247, in query_inplay_scores\n    scores = "
                            },
                            {
                                "type": "link",
                                "url": "http:\/\/self.trading.in",
                                "text": "self.trading.in"
                            },
                            {
                                "type": "text",
                                "text": "_play_service.get_scores(event_ids=event_ids)\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/inplayservice.py\", line 99, in get_scores\n    return self.process_response(\n  File \"\/home\/code\/PycharmProjects\/venv\/lib\/python3.8\/site-packages\/betfairlightweight\/endpoints\/baseendpoint.py\", line 110, in process_response\n    raise InvalidResponse(response=result)\nbetfairlightweight.exceptions.InvalidResponse: Invalid response received:"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UE72WCRR8",
        "type": "message",
        "ts": "1611083044.018500",
        "edited": {
            "user": "UE72WCRR8",
            "ts": "1611083075.000000"
        },
        "client_msg_id": "1e0985f3-c5cf-4a90-86d0-4aab31c8734b",
        "text": "should I make an issue on github?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "7872271afbd5",
            "image_72": "https:\/\/avatars.slack-edge.com\/2019-09-18\/751973528338_7872271afbd5e88918d9_72.jpg",
            "first_name": "",
            "real_name": "John",
            "display_name": "jhaa",
            "team": "T4G9NBD2M",
            "name": "jhaa",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "gv9vd",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "should I make an issue on github?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1611083109.019300",
        "client_msg_id": "06B05B37-A169-43C2-A79A-C7A72CDEA8A9",
        "text": "Yeah, if you have the response that would be great to see what the error is ",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "QRK7",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Yeah, if you have the response that would be great to see what the error is "
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UE72WCRR8",
        "type": "message",
        "ts": "1611083125.019600",
        "client_msg_id": "71cf0177-b84b-4470-b0d1-633df74a5e3a",
        "text": "ok cool, it is very long the response and did not fit here",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "7872271afbd5",
            "image_72": "https:\/\/avatars.slack-edge.com\/2019-09-18\/751973528338_7872271afbd5e88918d9_72.jpg",
            "first_name": "",
            "real_name": "John",
            "display_name": "jhaa",
            "team": "T4G9NBD2M",
            "name": "jhaa",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "6gj",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "ok cool, it is very long the response and did not fit here"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1611083575.021300",
        "client_msg_id": "222F2D22-68BB-4DA9-A522-AFF1EB1E796F",
        "text": "Cheers, I think we are always going to have problems with these undocumented endpoints and resource creation, lightweight mode gets around this of course but raw dicts aren’t for everyone ",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "uIe",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Cheers, I think we are always going to have problems with these undocumented endpoints and resource creation, lightweight mode gets around this of course but raw dicts aren’t for everyone "
                            }
                        ]
                    }
                ]
            }
        ]
    }
]