[
    {
        "user": "U04380WMKL2",
        "type": "message",
        "ts": "1665960515.212209",
        "client_msg_id": "79cec085-c1e9-46c7-9660-5563f78e3915",
        "text": "Unfortunately yes, I also tried running in Jupyter Notebook, but I am getting the exact same error. Do I perhaps need to update some packages?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "0689a341f842",
            "image_72": "https:\/\/avatars.slack-edge.com\/2022-10-11\/4205481052053_0689a341f84245209a1b_72.png",
            "first_name": "Liam",
            "real_name": "Liam Querido",
            "display_name": "Liam Querido",
            "team": "T4G9NBD2M",
            "name": "liamquerido",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1665619955.650719",
        "parent_user_id": "U04380WMKL2",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "oMb",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Unfortunately yes, I also tried running in Jupyter Notebook, but I am getting the exact same error. Do I perhaps need to update some packages?"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]