[
    {
        "text": "Just noticed I'm getting status 503's on some (but not all instances), not seen this before..\nStill seem to have placed some orders in the first rave today though...\nI guess I just restart them?",
        "files": [
            {
                "id": "F060S983YJK",
                "mode": "hidden_by_limit"
            }
        ],
        "upload": false,
        "user": "UQL0QDEKA",
        "display_as_bot": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "+WdDz",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Just noticed I'm getting status 503's on some (but not all instances), not seen this before..\nStill seem to have placed some orders in the first rave today though...\nI guess I just restart them?"
                            }
                        ]
                    }
                ]
            }
        ],
        "type": "message",
        "ts": "1697372027.233329",
        "client_msg_id": "be674784-e140-49b1-a0cd-b39bbade5984",
        "thread_ts": "1697372027.233329",
        "reply_count": 2,
        "reply_users_count": 2,
        "latest_reply": "1697381017.991769",
        "reply_users": [
            "U4H19D1D2",
            "UQL0QDEKA"
        ],
        "replies": [
            {
                "user": "U4H19D1D2",
                "ts": "1697380720.139509"
            },
            {
                "user": "UQL0QDEKA",
                "ts": "1697381017.991769"
            }
        ],
        "is_locked": false,
        "subscribed": true,
        "last_read": "1697381017.991769"
    },
    {
        "user": "UQL0QDEKA",
        "type": "message",
        "ts": "1697372311.933609",
        "edited": {
            "user": "UQL0QDEKA",
            "ts": "1697372326.000000"
        },
        "client_msg_id": "8ff7e448-9998-4334-84c8-2ead698b328d",
        "text": "Edit : All restarted; seems ok now",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g444d10128c0",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/444d10128c0aaf094041a52a76796602.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0005-72.png",
            "first_name": "Peter",
            "real_name": "Peter Lenagh",
            "display_name": "PeterLe",
            "team": "T4G9NBD2M",
            "name": "lenagh",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "l2nqZ",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Edit : All restarted; seems ok now"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1697380720.139509",
        "client_msg_id": "32E91374-D255-4690-9650-13BC4756A107",
        "text": "That’s very weird, I imagine <@UNW8Q88EL> might be interested in a connectionId ",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1697372027.233329",
        "parent_user_id": "UQL0QDEKA",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "dDq4q",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "That’s"
                            },
                            {
                                "type": "text",
                                "text": " very weird, I imagine "
                            },
                            {
                                "type": "user",
                                "user_id": "UNW8Q88EL"
                            },
                            {
                                "type": "text",
                                "text": " might be interested in a connectionId "
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UQL0QDEKA",
        "type": "message",
        "ts": "1697381017.991769",
        "client_msg_id": "eec0227f-72a8-4d00-8dee-d7cab857f26b",
        "text": "Im running four instances Liam on the same AWS instance, three were giving that error (if Ive checked it correctly and didnt miss it on the one I thought was OK..)\nThe one that looked ok -  I restarted that one yesterday after I changed some parameters? Not sure if that had something t do with it?\nAnyway, all good now, been a good day so far :grinning:",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g444d10128c0",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/444d10128c0aaf094041a52a76796602.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0005-72.png",
            "first_name": "Peter",
            "real_name": "Peter Lenagh",
            "display_name": "PeterLe",
            "team": "T4G9NBD2M",
            "name": "lenagh",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1697372027.233329",
        "parent_user_id": "UQL0QDEKA",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "+mwYK",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Im running four instances Liam on the same AWS instance, three were giving that error (if Ive checked it correctly and didnt miss it on the one I thought was OK..)\nThe one that looked ok -  I restarted that one yesterday after I changed some parameters? Not sure if that had something t do with it?\nAnyway, all good now, been a good day so far "
                            },
                            {
                                "type": "emoji",
                                "name": "grinning",
                                "unicode": "1f600"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U03B4S0K1T2",
        "type": "message",
        "ts": "1697412350.598979",
        "edited": {
            "user": "U03B4S0K1T2",
            "ts": "1697414331.000000"
        },
        "client_msg_id": "240c10be-17c7-4e26-a93a-ecaf87eab7ff",
        "text": "I'm having trouble running the marketrecorder located at flumine\/examples\/strategies\/marketrecorder.py within the flumine Git repository. It seems that the process_raw_data is not being executed. Do I need to make any changes to the marketrecorder (such as returning True in the check_market_book or passing the strategy's stream_class as DataStream instead of MarketStream)?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "cc253c3f37f9",
            "image_72": "https:\/\/avatars.slack-edge.com\/2022-04-06\/3348480972038_cc253c3f37f9d424c465_72.png",
            "first_name": "Andrey",
            "real_name": "Andrey Luiz Malheiros",
            "display_name": "Andrey Luiz Malheiros",
            "team": "T4G9NBD2M",
            "name": "andreylcj",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1697412350.598979",
        "reply_count": 2,
        "reply_users_count": 2,
        "latest_reply": "1697476980.211469",
        "reply_users": [
            "U4H19D1D2",
            "U03B4S0K1T2"
        ],
        "replies": [
            {
                "user": "U4H19D1D2",
                "ts": "1697437331.361619"
            },
            {
                "user": "U03B4S0K1T2",
                "ts": "1697476980.211469"
            }
        ],
        "is_locked": false,
        "subscribed": true,
        "last_read": "1697476980.211469",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "m3Wt9",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I'm having trouble running the marketrecorder located at flumine\/examples\/strategies\/marketrecorder.py within the flumine Git repository. It seems that the process_raw_data is not being executed. Do I need to make any changes to the marketrecorder (such as returning True in the check_market_book or passing the strategy's stream_class as DataStream instead of MarketStream)?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1697437331.361619",
        "client_msg_id": "C839F053-0628-43F7-A066-FC92EDFBEBB7",
        "text": "What do the logs say?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1697412350.598979",
        "parent_user_id": "U03B4S0K1T2",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "MYgtz",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "What do the logs say?"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]