[
    {
        "user": "U02RN7YDRQ9",
        "type": "message",
        "ts": "1689939863.120259",
        "client_msg_id": "adf48b09-2f0c-47c1-be4a-71b6c96edecf",
        "text": "Sorry, seem to have managed to break the shin() implementation <@UBS7QANF3> This was a backtest on a race with only 3 active runners. Occurred on only a couple of races in many thousands. Digging around, came up with the code below that crashes in console. Running latest v0.0.2 under Python 3.9. Think the maths is above my pay grade lol.\n\n```import shin\nodds = [2.08, 2.12, 3]\t# back odds - works ok\nshinDict = shin.calculate_implied_probabilities(odds)\nprint(shinDict)\nodds = [5, 10, 20]\t# lay odds - OverflowError (34, 'Result too large')\nshinDict = shin.calculate_implied_probabilities(odds)\nprint(shinDict)```",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "ge46f1f8b708",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/e46f1f8b708a630e3191de7b2c42b1d1.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0023-72.png",
            "first_name": "edblock",
            "real_name": "edblock",
            "display_name": "foxwood",
            "team": "T4G9NBD2M",
            "name": "eanb",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1689939863.120259",
        "reply_count": 4,
        "reply_users_count": 2,
        "latest_reply": "1689940969.829119",
        "reply_users": [
            "UBS7QANF3",
            "U02RN7YDRQ9"
        ],
        "replies": [
            {
                "user": "UBS7QANF3",
                "ts": "1689940106.994719"
            },
            {
                "user": "U02RN7YDRQ9",
                "ts": "1689940492.096629"
            },
            {
                "user": "UBS7QANF3",
                "ts": "1689940548.026009"
            },
            {
                "user": "U02RN7YDRQ9",
                "ts": "1689940969.829119"
            }
        ],
        "is_locked": false,
        "subscribed": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "LeR",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Sorry, seem to have managed to break the shin() implementation "
                            },
                            {
                                "type": "user",
                                "user_id": "UBS7QANF3"
                            },
                            {
                                "type": "text",
                                "text": " This was a backtest on a race with only 3 active runners. Occurred on only a couple of races in many thousands. Digging around, came up with the code below that crashes in console. Running latest v0.0.2 under Python 3.9. Think the maths is above my pay grade lol.\n\n"
                            }
                        ]
                    },
                    {
                        "type": "rich_text_preformatted",
                        "elements": [
                            {
                                "type": "text",
                                "text": "import shin\nodds = [2.08, 2.12, 3]\t# back odds - works ok\nshinDict = shin.calculate_implied_probabilities(odds)\nprint(shinDict)\nodds = [5, 10, 20]\t# lay odds - OverflowError (34, 'Result too large')\nshinDict = shin.calculate_implied_probabilities(odds)\nprint(shinDict)"
                            }
                        ],
                        "border": 0
                    }
                ]
            }
        ]
    },
    {
        "user": "UBS7QANF3",
        "type": "message",
        "ts": "1689940106.994719",
        "client_msg_id": "36c0d329-044c-4e83-b5c0-39a1ebb1fc71",
        "text": "That market looks too deficient to get anything meaningful - 35% underround",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gaaf844a4a90",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/eaaf844a4a905431d83430e563b077aa.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0011-72.png",
            "first_name": "",
            "real_name": "Maurice Berk",
            "display_name": "Mo",
            "team": "T4G9NBD2M",
            "name": "maurice",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1689939863.120259",
        "parent_user_id": "U02RN7YDRQ9",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "BN8RV",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "That market looks too deficient to get anything meaningful - 35% underround"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U02RN7YDRQ9",
        "type": "message",
        "ts": "1689940492.096629",
        "client_msg_id": "cc77120b-4fc3-464b-9cc2-19c80d9c4cc0",
        "text": "I think it was a BF issue at the time - the actual race had 6 dogs  and none were reserves. Only 3 were marked as ACTIVE in market_book.runners and 3 as REMOVED. Just a weird combo that crashes with exception though.",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "ge46f1f8b708",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/e46f1f8b708a630e3191de7b2c42b1d1.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0023-72.png",
            "first_name": "edblock",
            "real_name": "edblock",
            "display_name": "foxwood",
            "team": "T4G9NBD2M",
            "name": "eanb",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1689939863.120259",
        "parent_user_id": "U02RN7YDRQ9",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "qmEI",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I think it was a BF issue at the time - the actual race had 6 dogs  and none were reserves. Only 3 were marked as ACTIVE in market_book.runners and 3 as REMOVED. Just a weird combo that crashes with exception though."
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UBS7QANF3",
        "type": "message",
        "ts": "1689940548.026009",
        "client_msg_id": "82e7c4f5-e121-4baf-818d-78fecd5f1d73",
        "text": "The package could definitely do with some better error handling",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gaaf844a4a90",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/eaaf844a4a905431d83430e563b077aa.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0011-72.png",
            "first_name": "",
            "real_name": "Maurice Berk",
            "display_name": "Mo",
            "team": "T4G9NBD2M",
            "name": "maurice",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1689939863.120259",
        "parent_user_id": "U02RN7YDRQ9",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "bCuEj",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "The package could definitely do with some better error handling"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U02RN7YDRQ9",
        "type": "message",
        "ts": "1689940969.829119",
        "client_msg_id": "a0369a9f-fef6-4fb9-a00f-2e5f8c1ea835",
        "text": "I had wrapped it in a try call cos broke on back odds at some point. The exception was handled by just calling shin for the lay odds and no exception from that was allowed for lol. Will change my code to cope with the error.",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "ge46f1f8b708",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/e46f1f8b708a630e3191de7b2c42b1d1.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0023-72.png",
            "first_name": "edblock",
            "real_name": "edblock",
            "display_name": "foxwood",
            "team": "T4G9NBD2M",
            "name": "eanb",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1689939863.120259",
        "parent_user_id": "U02RN7YDRQ9",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "48u2",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I had wrapped it in a try call cos broke on back odds at some point. The exception was handled by just calling shin for the lay odds and no exception from that was allowed for lol. Will change my code to cope with the error."
                            }
                        ]
                    }
                ]
            }
        ]
    }
]