[
    {
        "user": "UBS7QANF3",
        "type": "message",
        "ts": "1681717465.151159",
        "client_msg_id": "2577948d-b102-476b-81fe-f5744d6c4bd9",
        "text": "What version of Python are you running?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gaaf844a4a90",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/eaaf844a4a905431d83430e563b077aa.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0011-72.png",
            "first_name": "",
            "real_name": "Maurice Berk",
            "display_name": "Mo",
            "team": "T4G9NBD2M",
            "name": "maurice",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1681665134.137979",
        "parent_user_id": "U053U2PUK2M",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "QNHvw",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "What version of Python are you running?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U053ETSL666",
        "type": "message",
        "ts": "1681730894.345109",
        "client_msg_id": "1190e4fb-eea0-4a49-bdeb-de752c9ddcc4",
        "text": "Thanks - think I missed that step!",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "3c454572d52e",
            "image_72": "https:\/\/avatars.slack-edge.com\/2023-04-16\/5113998876981_3c454572d52eaeddbd41_72.png",
            "first_name": "alan",
            "real_name": "alan fisher",
            "display_name": "alan fisher",
            "team": "T4G9NBD2M",
            "name": "fishea000",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1681638139.747009",
        "parent_user_id": "U053ETSL666",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "e0P4",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Thanks - think I missed that step!"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U053U2PUK2M",
        "type": "message",
        "ts": "1681753786.704769",
        "client_msg_id": "f0024d8a-b231-4467-9ca4-8fdcba75e381",
        "text": "This is with python 3.9.16 and betfairlightweight==2.17.1\n\nThe login is successful within a docker container locally however I am deploying this container within a custom training job on google cloud platform and that is where I'm experiencing this error.",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "cd650a2c5d10",
            "image_72": "https:\/\/avatars.slack-edge.com\/2023-04-16\/5114523896437_cd650a2c5d1024b02e08_72.png",
            "first_name": "eugene",
            "real_name": "eugene brown",
            "display_name": "eugene brown",
            "team": "T4G9NBD2M",
            "name": "efbbrown",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1681665134.137979",
        "parent_user_id": "U053U2PUK2M",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "iF2q",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "This is with python 3.9.16 and betfairlightweight==2.17.1\n\nThe login is successful within a docker container locally however I am deploying this container within a custom training job on google cloud platform and that is where I'm experiencing this error."
                            }
                        ]
                    }
                ]
            }
        ]
    }
]